
--자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기
--https://school.programmers.co.kr/learn/courses/30/lessons/157340
SELECT 
DISTINCT(CAR_ID), 
CASE WHEN CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE) THEN '대여중'
ELSE '대여 가능' 
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC


--https://school.programmers.co.kr/learn/courses/30/lessons/151139
--대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT DATE_FORMAT(START_DATE,'%m') AS MONTH, CAR_ID, count(car_id) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' and '2022-10'
          GROUP BY CAR_ID
          HAVING COUNT(CAR_ID)>=5)
# count 출력을 위한 추가 조건
and DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' and '2022-10'
GROUP BY MONTH, CAR_ID 
ORDER BY MONTH, CAR_ID DESC
