'''
point
- GROUP BY로 CAR_ID 묶어줘야 함
- 날짜 기한 조건 생각하기

알게 된 것
- FLOOR -> 버림
'''

  https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT a.CAR_ID, a.CAR_TYPE, FLOOR(a.DAILY_FEE * 30* (100 - c.discount_rate)*0.01) as FEE
FROM CAR_RENTAL_COMPANY_CAR a 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c on a.CAR_TYPE = c.CAR_TYPE 
WHERE a.CAR_ID not in (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
)
and c.DURATION_TYPE like '30일%'
GROUP BY a.CAR_ID
HAVING a.CAR_TYPE in('SUV', '세단')
AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE , CAR_ID DESC
